### ISSUE TITLE
[Feature Request]: Apicurio Registry support

### ISSUE THREAD

**Issue by brendonvicente** [Farfetch/kafkaflow#350]
### Describe the solution you'd like

It would be awesome to be able to use the apicurio registry to get more features.

https://www.apicur.io/registry/docs/apicurio-registry/2.3.x/getting-started/assembly-intro-to-the-registry.html
https://www.apicur.io/registry/docs/apicurio-registry/2.3.x/assets-attachments/registry-rest-api.htm

### Are you able to help bring it to life and contribute with a Pull Request?

No

**Comment by gsferreira** [comment]
Hi @brendonvicente 

Thank you for taking the time to submit this feature request!

We plan to grow an extension ecosystem and keep the Core project as lean as possible. Since we see value in having Apicurio as a Registry, we kindly ask you if you would like to publish an extension to KafkaFlow on your own. 
You would create a GitHub Repo with the Registry and publish it as a NuGet package.
Then, we would love to list it under our [Extensions list](https://farfetch.github.io/kafkaflow/extensions).

Let us know if you would like to move forward with it. We are more than happy to help you out.
