### ISSUE TITLE
[Bug Report]: KafkaBus.StopAsync() blocks and does not return if there are messages still pending to be consumed

### ISSUE THREAD

**Issue by massada** [Farfetch/kafkaflow#482]
### Prerequisites

- [X] I have searched [issues](https://github.com/Farfetch/kafkaflow/issues) to ensure it has not already been reported

### Description

KafkaBus.StopAsync() blocks and does not return if there are messages still pending to be consumed.

### Steps to reproduce

Produce various messages, lock the consumer (with a long delay for example) and call KafkaBus.StopAsync().

### Expected behavior

KafkaBus.StopAsync() should (quickly) stop even if there are messages in the workers buffer.

### Actual behavior

Within the stopping flow, PartitionOffsets.WaitContextsCompletionAsync() method is called to wait for all known received consumer contexts. This method waits for a task completion of each context. This task completion is never set (Complete() is never called).

### KafkaFlow version

v3.0.0

**Comment by joelfoliveira** [comment]
This behavior is expected, because KafkaFlow will try to complete the message processing before stopping in order to prevent duplication of message processing and to commit the offset accordingly.

In cases, where you have a long-running task to process the message you can use the WorkerStopped CancellationToken available through the IMessageContext (`messageContext.ConsumerContext.WorkerStopped`) to listen for the cancellation and to interrupt the message processing. By default, this token is canceled 30 seconds after the worker has been issued to stop processing. 
The time it takes for the cancellation can be changed using the Consumer Configuration method `.WithWorkerStopTimeout(...)`

**Comment by joelfoliveira** [comment]
Hi @massada ,

If you're still experiencing this issue or have any additional information to share, please feel free to let us know.

However, if we don't receive any updates or feedback from you within the next 5 business days, we may need to consider closing this issue. Please understand that this is not a final decision, and you can always reopen the issue or create a new one in the future.

We appreciate your contribution to our project and look forward to hearing from you soon. If you have any questions or need further assistance, don't hesitate to reach out.

**Comment by massada** [comment]
Hi @joelfoliveira,
Yes, I am. I’ve been talking with @filipeesch and we’ve found out a corner case where the message is processed faster than it is inserted in the offset manager, making it throw a exception when trying to complete it, and thus never completing it (not storing the offsets).
We’re have a fix but are still deciding the best approach to fix this.
